spring:
  application:
    name: forklift-directory
  datasource:
    url: jdbc:postgresql://localhost:5432/forklift-directory
    username: aliaksei
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          preferred_duration_jdbc_type: INTERVAL_SECOND
    show-sql: true
  sql:
    init:
      mode: always